version: '3.8'

services:
  web:
    build:
      context: .
    env_file:
      - .env
    command: gunicorn dcrm.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000

volumes:
  static_volume:
