version: '3.8'

services:
  web:
    env_file:
      - .env.production
    command: gunicorn dcrm.wsgi:application --bind 0.0.0.0:8000 --workers 4

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  static_volume:
