# Generated by Django 5.2.1 on 2025-05-22 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.SlugField(blank=True, unique=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("linkedin_profile", models.URLField(blank=True)),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("employee_count", models.CharField(blank=True, max_length=50)),
                ("campany_linkedin_page", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("linkedin_scrape", "LinkedIn Scrape"),
                            ("social", "Social Media"),
                            ("newsletter", "Newsletter Opt-in"),
                            ("form", "Free Consultation Form"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("cold", "Cold"),
                            ("warm", "Warm"),
                            ("hot", "Hot"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("intro", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("cta", models.CharField(blank=True, max_length=255)),
                ("ps", models.TextField(blank=True)),
                ("pps", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("landing_page_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_converted", models.BooleanField(default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="campaign.lead"
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "lead")},
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "utm_source",
                    models.CharField(default="email_outreach", max_length=100),
                ),
                ("utm_medium", models.CharField(default="email", max_length=100)),
                ("utm_campaign", models.CharField(max_length=100)),
                ("utm_term", models.CharField(blank=True, max_length=100)),
                ("utm_content", models.CharField(blank=True, max_length=100)),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference code for tracking",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("visited_at", models.DateTimeField(blank=True, null=True)),
                ("visit_count", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaign",
                    ),
                ),
                (
                    "campaign_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaignlead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_leads", models.IntegerField(default=0)),
                ("total_messages_sent", models.IntegerField(default=0)),
                ("total_opens", models.IntegerField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_conversions", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaign",
                    ),
                ),
                (
                    "best_cta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campaign.link",
                    ),
                ),
                (
                    "best_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campaign.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personlized_msg", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded", models.BooleanField(default=False)),
                ("responded_content", models.TextField(blank=True)),
                (
                    "campaign_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaignlead",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.message",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign.link",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed", models.BooleanField(default=False)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign.lead",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaign.product"
            ),
        ),
    ]
