# Generated by Django 5.2.1 on 2025-05-22 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="link",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description of this link's purpose",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("message", "Email Message"),
                    ("social", "Social Media"),
                    ("manual", "Manual Sharing"),
                    ("other", "Other"),
                ],
                default="message",
                help_text="What this link will be used for",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="ref",
            field=models.CharField(
                blank=True,
                help_text="Unique reference code for tracking (auto-generated if left empty)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Will be auto-populated from campaign's product landing page if left empty",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="Will be auto-populated from campaign's short_name if left empty",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="messageassignment",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_assignments",
                to="campaign.link",
            ),
        ),
    ]
