# Generated by Django 5.2.1 on 2025-05-31 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageassignment",
            name="newsletter_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Link for newsletter signup",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newsletter_message_assignments",
                to="campaign.link",
            ),
        ),
    ]
