# Generated by Django 5.2.1 on 2025-05-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_link_created_at_link_description_link_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageassignment",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaign.campaign",
            ),
        ),
    ]
