# Generated by Django 5.2.1 on 2025-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_messageassignment_campaign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messageassignment",
            old_name="personlized_msg",
            new_name="personlized_msg_tmp",
        ),
        migrations.AddField(
            model_name="messageassignment",
            name="personlized_msg_to_send",
            field=models.TextField(blank=True),
        ),
    ]
