# Generated by Django 5.2.1 on 2025-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaign",
            "0004_rename_personlized_msg_messageassignment_personlized_msg_tmp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="full_content",
            field=models.TextField(blank=True),
        ),
    ]
