# Generated by Django 5.2.1 on 2025-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_message_full_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="end",
            field=models.CharField(default="best,", max_length=255),
            preserve_default=False,
        ),
    ]
