# Generated by Django 5.2.1 on 2025-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0006_message_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="end",
            field=models.TextField(max_length=255),
        ),
    ]
