# Generated by Django 5.2.1 on 2025-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0007_alter_message_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageassignment",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
